nodeLinker: node-modules

npmScopes:
  awesome.me:
    npmAlwaysAuth: true
    npmAuthToken: 779E1F31-CF8A-49FF-B245-2A67E31C598B
    npmRegistryServer: "https://npm.fontawesome.com/"
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: 779E1F31-CF8A-49FF-B245-2A67E31C598B
    npmRegistryServer: "https://npm.fontawesome.com/"
