const getSequence = ():string[] => {
  return []
}

export const pureRandom = [
'Connection secured. Monitoring for external activity.',
'[STATUS: GREEN] All nodes stable. Awaiting input.',
'No abnormal traffic detected. System functioning within parameters.',
'Firewall protocols active. No intrusions logged.',
'Network encrypted [4096-bit]. Idle state.',
'[INFO] Secure handshake confirmed. Latency: 12ms.',
'Background processes running smoothly. No anomalies detected.',
'Idle state. All systems nominal.',
'Encryption integrity confirmed. Awaiting further commands.',
'Node status: [ONLINE]. Load: [32%]. Monitoring connections.',
'Routine background scan initiated. No threats found.',
'All secure directories remain locked. Monitoring data vaults.',
'Packet stream stabilized. Current activity: Low.',
'[INFO] Encrypted storage accessible. No external pings detected.',
'System on standby. Ready to engage at operator command.',
'[STATUS: NOMINAL] All sectors operational. No irregularities found.',
'Load distribution balanced. System temperature stable.',
'No unauthorized login attempts detected.',
'Passive network scan running. Results pending.',
'Automated log scrubbing in progress. No alerts to report.',
'[INFO] Next scheduled system purge in 12 hours.',
'Idle processes maintained. Command input expected.',
'No new messages in secure channels.',
'Status update: No active threats. Monitoring for activity.',
'Secure backup completed. Awaiting further instructions.',
'[NOTICE] User "X39-K9" logged in. Monitoring activity...',
'User "Ghost_87" has accessed secure directories.',
'Node traffic spike detected from user "Slipstream."',
'[INFO] User "NovaFang" just uploaded a new data cache.',
'[ALERT] User "BlackCat" accessing high-security tier.',
'Warning: User "Specter" bypassed standard authentication protocols.',
'[INFO] User "IceBreaker" requesting file decryption assistance.',
'[SECURE NOTICE] User "Seraph-92" connected from hidden node...',
'Private communication established between users "Hexed" and "Shadow."',
'Active connections: 23. Scanning for anomalies...',
'[INFO] System activity spike at node 42C. Redirecting load...',
'Latency detected in packet stream: Rerouting data flow.',
'Inactive users detected: Forcing disconnection on idle nodes...',
'[ALERT] Unusual packet activity from external network detected.',
'Proxy server engaged: Redirecting all unsecured connections.',
'Load balancing initiated on congested node 8F3.',
'Background data purge scheduled at 04:12:59.',
'[NOTICE] Data cache is being mirrored to external servers.',
'Error in data stream on node 451: Attempting auto-repair.',
'High-risk files being quarantined in vault sector 9X...',
'Node traffic saturation detected. Deflecting data packets.',
'[INFO] Backups initiated across multi-node system grid.',
'[NOTICE] Data vault protocols upgraded: Encryption level 7 applied.',
'[INFO] User "ZeroCipher" just pulled encrypted files from sector 7B.',
'[LOG] User "Ghost_87" initiated a secure file transfer...',
'[NOTICE] User "Overclock" scanned system logs at 01:23:45.',
'File transfer completed: User "Redline" uploaded payload to shared drive.',
'Data archive opened by "Nexus_Echo" in hidden directory 12...',
'User "Pulse" executed deletion protocol on compromised sector.',
'[INFO] User "BlackLotus" is routing traffic through multiple proxies.',
'[LOG] User "Wraith" is running deep search protocol on node 13B.',
'Transaction initiated between users "Marauder" and "Spire".',
'[NOTICE] User "Spectre_X" accessed restricted comms network.',
'Active connections: 23. Scanning for anomalies...',
'[INFO] System activity spike at node 42C. Redirecting load...',
'Latency detected in packet stream: Rerouting data flow.',
'Inactive users detected: Forcing disconnection on idle nodes...',
'[ALERT] Unusual packet activity from external network detected.',
'Proxy server engaged: Redirecting all unsecured connections.',
'Load balancing initiated on congested node 8F3.',
'Background data purge scheduled at 04:12:59.',
'[NOTICE] Data cache is being mirrored to external servers.',
'Error in data stream on node 451: Attempting auto-repair.',
'High-risk files being quarantined in vault sector 9X...',
'Node traffic saturation detected. Deflecting data packets.',
'[INFO] Backups initiated across multi-node system grid.',
'[NOTICE] Data vault protocols upgraded: Encryption level 7 applied.',
]

const login = [
'Establishing secure tunnel...',
'Initiating multi-tier handshake...',
'Encrypting connection [--------------------]  00%',
'Encrypting connection [████----------------]  21%',
'Encrypting connection [████████------------]  30%',
'Encrypting connection [████████████████----]  74%',
'Encrypting connection [████████████████████] 100%',
'Verifying remote node authenticity...',
'[AUTH_OK] Remote node confirmed.',
'Handshake complete. Secure connection established.',
]

const advice = [
  'Incoming system message: "Never trust the first handshake"',
  'Incoming system message: "Never trust a dragon"',
  'Incoming system message: "The blade in hand isn\'t in your spine"',
  'Incoming system message: "Don\'t track spiders"',
]